#!/usr/bin/env python3
"""Turn the ASCII sprites in tools/sprites/ into box-shadow CSS.

The games this site links to compose their sprites at boot from pixel
matrices. The page does the same thing, except a stylesheet cannot loop, so
the matrices are expanded here and pasted between the markers in style.css.

    python3 tools/build-sprites.py           # rewrite the block in style.css
    python3 tools/build-sprites.py --check   # fail if the block is stale
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPRITES = ROOT / "tools" / "sprites"
STYLESHEET = ROOT / "style.css"
BEGIN = "/* SPRITES:BEGIN — generated by tools/build-sprites.py, do not edit */"
END = "/* SPRITES:END */"


def parse(path: pathlib.Path) -> tuple[str, list[str], dict[str, str]]:
    name, palette, rows = path.stem, {}, []
    for line in path.read_text().splitlines():
        if line.startswith("#"):
            body = line.lstrip("#").strip()
            if body.startswith("name:"):
                name = body.split(":", 1)[1].strip()
            else:
                for pair in body.split():
                    key, _, value = pair.partition("=")
                    palette[key] = value
        elif line.strip():
            rows.append(line)

    widths = {len(row) for row in rows}
    if len(widths) != 1:
        raise SystemExit(f"{path.name}: rows are ragged, widths {sorted(widths)}")
    unknown = {c for row in rows for c in row} - set(palette) - {"."}
    if unknown:
        raise SystemExit(f"{path.name}: no colour for {sorted(unknown)}")
    return name, rows, palette


def to_css(name: str, rows: list[str], palette: dict[str, str]) -> str:
    shadows = [
        f"calc(var(--px) * {x}) calc(var(--px) * {y}) 0 0 {palette[c]}"
        for y, row in enumerate(rows)
        for x, c in enumerate(row)
        if c != "."
    ]
    joined = ",\n    ".join(shadows)
    # The dimensions go on the actor so it can size itself; the shadows go on
    # the single pixel inside it, which every offset is measured from.
    return (
        f".actor--{name} {{\n"
        f"  --cols: {len(rows[0])};\n"
        f"  --rows: {len(rows)};\n"
        f"}}\n\n"
        f".actor--{name} .pixel {{\n"
        f"  box-shadow:\n    {joined};\n"
        f"}}"
    )


def build() -> str:
    blocks = [to_css(*parse(p)) for p in sorted(SPRITES.glob("*.txt"))]
    return "\n\n".join(blocks)


def main() -> int:
    generated = build()
    css = STYLESHEET.read_text()
    if BEGIN not in css or END not in css:
        raise SystemExit(f"markers missing from {STYLESHEET.name}")

    head, rest = css.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = f"{head}{BEGIN}\n\n{generated}\n\n{END}{tail}"

    if "--check" in sys.argv:
        if updated != css:
            print("style.css is out of date; run tools/build-sprites.py", file=sys.stderr)
            return 1
        print("sprites are up to date")
        return 0

    STYLESHEET.write_text(updated)
    sprites = len(list(SPRITES.glob("*.txt")))
    pixels = generated.count("calc(var(--px)") // 2
    print(f"wrote {sprites} sprites, {pixels} pixels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
